### PR TITLE
[MINE-1] Migrated to project structure generated by the KMP Wizard

### PR DESCRIPTION
**Pull request by Xacalet**
- For Android and desktop targets, code from top-level modules and common module has been modified and moved to `:ComposeApp` module (previously `common` module).
- iOS target is now ran through an XCode project in `iOSApp`.
- Image and font resources are now properly retrieved by all targets (Android/iOS/desktop/JS).
- Updated library versions.

### CODE REVIEW

**Comment by serbelga** [comment]
You can remove `web` module and move `main.js.kt` from `web` module to `composeApp` jsMain in package:
`com.xacalet.minesweeper.compose.app`.

Also, `main.kt` file in `desktopMain` could be on `com.xacalet.minesweeper.compose.app` instead of `kotlin` folder. That refactor would require updating `mainClass` in `build.gradle.kts`

```kotlin
compose.desktop {
    application {
        mainClass = "com.xacalet.minesweeper.compose.app.MainKt"
```

same for `MainViewController` in iosMain, could be moved to `com.xacalet.minesweeper.compose.app` package.

**Comment by serbelga** [comment]
Since `common` module has been renamed to `composeApp`, package name for files under this module could be renamed:

```diff
-package com.xacalet.minesweeper.common.ui
+package com.xacalet.minesweeper.compose.app.ui
```

or 

```diff
-package com.xacalet.minesweeper.common.ui
+package com.xacalet.minesweeper.composeapp.ui
```

**Review by serbelga — APPROVED** [review]

**Comment by Xacalet** [comment]
> You can remove `web` module and move `main.js.kt` from `web` module to `composeApp` jsMain in package: `com.xacalet.minesweeper.compose.app`.
> 
> Also, `main.kt` file in `desktopMain` could be on `com.xacalet.minesweeper.compose.app` instead of `kotlin` folder. That refactor would require updating `mainClass` in `build.gradle.kts`
> 
> ```kotlin
> compose.desktop {
>     application {
>         mainClass = "com.xacalet.minesweeper.compose.app.MainKt"
> ```
> 
> same for `MainViewController` in iosMain, could be moved to `com.xacalet.minesweeper.compose.app` package.

I wasn't able to succeed on that. The only results I got were failing on build or running the web app but without the composeApp being displayed. As this target is still on a experimental stage, I decided to wait until it reaches at least alpha.

**Comment by Xacalet** [comment]
> You can remove `web` module and move `main.js.kt` from `web` module to `composeApp` jsMain in package: `com.xacalet.minesweeper.compose.app`.
> 
> Also, `main.kt` file in `desktopMain` could be on `com.xacalet.minesweeper.compose.app` instead of `kotlin` folder. That refactor would require updating `mainClass` in `build.gradle.kts`
> 
> ```kotlin
> compose.desktop {
>     application {
>         mainClass = "com.xacalet.minesweeper.compose.app.MainKt"
> ```
> 
> same for `MainViewController` in iosMain, could be moved to `com.xacalet.minesweeper.compose.app` package.

Regarding the `web` module, I couldn't include its migration in the first commit as I wasn't able to run the app succesfully after moving everything to from `:web` to `:composeApp:jsMain`. Checking [another Compose wizard]((https://terrakok.github.io/Compose-Multiplatform-Wizard/)) which, unlike the one provided by JetBrains, it does include web as a target, I realised that the js file referrenced in `index.html` must match the name of the Gradle that runs the web app (e.g. `composeApp.js`).

About the location of the `main.kt` files: I'm seeing as a common practice to keep these files in the root of the source set, out of any package. Honestly, I don't know the rationale behind this, but I think it's OK to follow that convention.

**Comment by Xacalet** [comment]
> Since `common` module has been renamed to `composeApp`, package name for files under this module could be renamed:
> 
> ```diff
> -package com.xacalet.minesweeper.common.ui
> +package com.xacalet.minesweeper.compose.app.ui
> ```
> 
> or
> 
> ```diff
> -package com.xacalet.minesweeper.common.ui
> +package com.xacalet.minesweeper.composeapp.ui
> ```

I've ended up removing the `common` package infix. It made sense when we had a `common` module, but know that the whole app is inside `composeApp`, it would just add redundancy.

**Pull request merged**
